"""``nightshift init`` — bootstrap command — Session 16.

Sets up a new project with nightshift scaffolding in one command:

* Creates ``nightshift.toml`` with sensible defaults
* Creates ``docs/`` directory with placeholder files
* Creates ``NIGHTSHIFT_LOG.md`` with a session-0 entry
* Creates ``.github/workflows/nightshift.yml`` CI workflow
* Creates ``CHANGELOG.md`` stub
* Optionally creates a ``src/`` directory with ``__init__.py``

All operations are idempotent — running ``nightshift init`` on an already-
initialised repo will not overwrite existing files unless ``--force`` is used.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class InitResult:
    """Summary of what ``nightshift init`` created."""

    created: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    repo_path: str = ""

    @property
    def total_created(self) -> int:
        return len(self.created)

    def to_dict(self) -> dict:
        return {
            "created": self.created,
            "skipped": self.skipped,
            "total_created": self.total_created,
            "repo_path": self.repo_path,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)

    def to_markdown(self) -> str:
        lines = ["# Nightshift Init\n"]
        lines.append(f"**Repo:** `{self.repo_path}`\n")
        if self.created:
            lines.append(f"## Created ({len(self.created)} files)\n")
            for f in self.created:
                lines.append(f"- \u2705 `{f}`")
            lines.append("")
        if self.skipped:
            lines.append(f"## Skipped (already exist)\n")
            for f in self.skipped:
                lines.append(f"- \u23ed  `{f}`")
            lines.append("")
        lines.append("---")
        lines.append("Run `nightshift health` to verify your setup.")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# File templates
# ---------------------------------------------------------------------------

_NIGHTSHIFT_TOML = """\
# nightshift.toml \u2014 Nightshift configuration
# Generated by `nightshift init`

[thresholds]
health_score_min = 60.0
docstring_coverage_min = 0.5
max_line_length = 88
todo_warn_threshold = 10
coupling_instability_max = 0.8
complexity_cc_warn = 10
complexity_cc_critical = 20
dep_outdated_warn = 3

[output]
default_format = "markdown"
color = true
unicode_symbols = true

[session]
session_log_path = "NIGHTSHIFT_LOG.md"
docs_dir = "docs"
src_dir = "src"
"""

_NIGHTSHIFT_LOG = """\
# Nightshift Session Log

This log records every autonomous development session run against this repo.

---

## Session 0 \u2014 Initialisation

**Operator:** nightshift init

**Tasks completed:**

- \u2705 Scaffolding created via `nightshift init`

**Stats snapshot:**

- Nights active: 0
- Total PRs: 0
- Test suite: 0 tests

---

*This log is maintained autonomously by Nightshift.*
"""

_CHANGELOG_MD = """\
# Changelog

All notable changes to this project are documented here.

The format follows [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
Semantic versioning is automated via `nightshift semver`.

---
"""

_GITHUB_WORKFLOW = """\
# .github/workflows/nightshift.yml
# Runs nightshift health check on every pull request.
name: Nightshift CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  nightshift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Nightshift
        run: pip install -e .

      - name: Run health check
        run: nightshift health

      - name: Run security audit
        run: nightshift security

      - name: Run dead code check
        run: nightshift deadcode
"""

_DOCS_README = """\
# docs/

This directory is managed by Nightshift.

| File | Generated by |
|------|--------------|
| `ARCHITECTURE.md` | `nightshift arch --write` |
| `coverage_history.json` | `nightshift run` |
| `maturity_report.md` | `nightshift maturity --write` |
| `dna.md` | `nightshift dna --write` |
| `story.md` | `nightshift story --write` |
| `audit_report.md` | `nightshift audit --write` |
| `semver_report.md` | `nightshift semver --write` |
| `benchmark_report.md` | `nightshift benchmark --write` |
| `git_stats.md` | `nightshift gitstats --write` |

Run `nightshift run --session <N>` to regenerate all docs for session N.
"""

_SRC_INIT = """\
\"\"\"Source package.\"\"\"
"""


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------

def _write_if_missing(path: Path, content: str, force: bool, result: InitResult) -> None:
    rel = str(path)
    if path.exists() and not force:
        result.skipped.append(rel)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    result.created.append(rel)


def bootstrap(repo_path: Path, force: bool = False, create_src: bool = False) -> InitResult:
    """
    Initialise a new repo with nightshift scaffolding.

    Parameters
    ----------
    repo_path:
        Root of the target repository.
    force:
        If True, overwrite existing files.
    create_src:
        If True, also create ``src/__init__.py``.

    Returns
    -------
    InitResult summarising what was created.
    """
    result = InitResult(repo_path=str(repo_path))

    _write_if_missing(repo_path / "nightshift.toml", _NIGHTSHIFT_TOML, force, result)
    _write_if_missing(repo_path / "NIGHTSHIFT_LOG.md", _NIGHTSHIFT_LOG, force, result)
    _write_if_missing(repo_path / "CHANGELOG.md", _CHANGELOG_MD, force, result)
    _write_if_missing(repo_path / "docs" / "README.md", _DOCS_README, force, result)
    _write_if_missing(
        repo_path / ".github" / "workflows" / "nightshift.yml",
        _GITHUB_WORKFLOW,
        force,
        result,
    )

    if create_src:
        _write_if_missing(repo_path / "src" / "__init__.py", _SRC_INIT, force, result)

    return result
